<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
  </properties>

  <groupId>io.github.filipemartinsdev</groupId>
  <artifactId>responsekit</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <name>responsekit</name>
  <description>A simple library with utility tools for Java REST applications</description>
  <url>https://github.com/filipemartinsdev/responsekit</url>

  <modules>
    <module>responsekit-core</module>
    <module>responsekit-spring-boot-starter</module>
    <module>responsekit-quarkus-extension</module>
  </modules>

</project>
