<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
  </properties>

  <parent>
    <groupId>io.github.filipemartinsdev</groupId>
    <artifactId>responsekit-parent</artifactId>
    <version>0.1.0</version>
  </parent>

  <artifactId>responsekit-spring-boot-starter</artifactId>
  <packaging>jar</packaging>

  <dependencies>
<!--    <dependency>-->
<!--      <groupId>io.github.filipemartinsdev</groupId>-->
<!--      <artifactId>responsekit-core</artifactId>-->
<!--      <version>${project.version}</version>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>io.github.filipemartinsdev</groupId>-->
<!--      <artifactId>responsekit-spring-boot-autoconfigure</artifactId>-->
<!--      <version>${project.version}</version>-->
<!--    </dependency>-->

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
